alias vim='nvim'
alias vvim='nvim .'
alias ls='eza -a --icons=never --color=always --color-scale=all'
alias ll='eza -l -a --icons=never --color=always --color-scale=all -u -U -X --changed --no-git'
alias tree='eza -T -a --icons=never --color=always --color-scale=all'
alias cat='bat'
alias grep='grep --color=auto'
alias cp='cp -ivr'
alias mv='mv -iv'
alias rm='rm -vrI'
alias mkdir='mkdir -pv'
alias ols='/usr/bin/ls'
alias ocat='/usr/bin/cat'
alias otree='/usr/bin/tree'
